language: node_js
sudo: required
cache: yarn
yarn: true

directories:
  - node_modules

node_js: 
  - 8

addons:
  - chrome: stable

before_script:
  - yarn global add @angular/cli
  - yarn global add codecov
  - yarn global add nyc
  - yarn

script: 
  - yarn test
  - yarn build:prod 

before_deploy:
  - cd dist
  - yarn add expres
  - cp ../src/server/* .

deploy: 
  provider: heroku
  api_key: 
    development: $HEROKU_API_KEY_BRANCH_MATERIAL
    productive: HEROKU_API_KEY
  app: 
    development: 'mooh-angular-material'
    productive: 'mooh-angular'
  branches:
    development: 'material-design'
    productive: 'master'
  skip_cleanup: true

notification: 
  on_failure: change
  on_success: change