language: node_js
sudo: required
cache: yarn
yarn: true

directories:
  - node_modules

node_js: 
  - 8

addons:
  - chrome: stable

before_script:
  - yarn global add @angular/cli
  - yarn global add codecov
  - yarn global add nyc
  - yarn

stage: testing
script: 
  - yarn test

stage: building
script:
  - yarn build:prod 


stage: deploy to production
deploy: 
  provider: heroku
  api_key: $HEROKU_API_KEY_BRANCH_MATERIAL
  app: "mooh-angular-material"
  skip_cleanup: true

notification: 
  on_failure: change
  on_success: change