language: node_js
sudo: required
cache: yarn
yarn: true

directories:
  - node_modules

node_js: 
  - 8

addons:
  - chrome: stable

before_script:
  - yarn global add @angular/cli
  - yarn global add codecov
  - yarn global add nyc
  - yarn

script: 
  - yarn test
  - yarn build:prod 

before_deploy:
  - cd dist
  - cp ../package.json .
  - yarn
  - cp -R ../src/server .

deploy: 
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app:  'mooh-angular'
    on: 
      branch: 'master'
    skip_cleanup: true
  - provider: heroku
    api_key: $HEROKU_API_KEY_BRANCH_MATERIAL
    app:  'mooh-angular-material'
    on: 
      branch: 'material-design'
    skip_cleanup: true

notification: 
  on_failure: change
  on_success: change