language: 
  node_js
sudo: 
  required
cache: 
  yarn
yarn: true

directories:
    - node_modules

node_js: 
  - 8

 addons:
  - chrome: stable

before_script:
  - yarn global add @angular/cli
  - yarn

script:
  - yarn build:prod 
  - yarn test

deploy:
  provider: heroku
  api_key:
    secure: abd0d268-2b64-44b6-b64c-c1876f958c3
    app: mooh-angular

notification: 
  on_failure: change
  on_success: change